**Proyecto Individual 1**

  ETL archivo: australian_users_reviews.jason

**IMPORTO LIBRERIAS**

In [153]:

import ast              # module Abstract Syntax Trees
import json             # module json encoder and decoder
import pandas as pd     # module panda Data Analysis Library
import nltk             # module nlkt - natural language toolkit

**CARGO ARCHIVO JSON A UN DATASETS**

In [154]:
# list 'output_steam_games.json'
rows = []
with open ('..\\JSON\\output_steam_games.json', 'r', encoding='utf-8') as f:
    for line in f.readlines():
        rows.append(json.loads(line))

# save to dF
df = pd.DataFrame(rows)
# tiempo 2.3s

In [155]:
df

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns"
120444,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,NaN,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24083 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   url           32135 non-null  object
 5   release_date  30068 non-null  object
 6   tags          31972 non-null  object
 7   reviews_url   32133 non-null  object
 8   specs         31465 non-null  object
 9   price         30758 non-null  object
 10  early_access  32135 non-null  object
 11  id            32133 non-null  object
 12  developer     28836 non-null  object
dtypes: object(13)
memory usage: 11.9+ MB

**ELIMINAMOS LOS REGISTROS CON VALORES NAN Y DUPLICADOS**

In [157]:
#Eliminamos cualquier registro que tenga al menos un NaN
df.dropna(how='any', inplace=True)

In [158]:
valores_nulos_por_columna = df.isnull().sum()
valores_nulos_por_columna

publisher       0
genres          0
app_name        0
title           0
url             0
release_date    0
tags            0
reviews_url     0
specs           0
price           0
early_access    0
id              0
developer       0
dtype: int64

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22530 entries, 88310 to 120443
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     22530 non-null  object
 1   genres        22530 non-null  object
 2   app_name      22530 non-null  object
 3   title         22530 non-null  object
 4   url           22530 non-null  object
 5   release_date  22530 non-null  object
 6   tags          22530 non-null  object
 7   reviews_url   22530 non-null  object
 8   specs         22530 non-null  object
 9   price         22530 non-null  object
 10  early_access  22530 non-null  object
 11  id            22530 non-null  object
 12  developer     22530 non-null  object
dtypes: object(13)
memory usage: 2.4+ MB

In [160]:
valores_nulos_por_columna = df.isnull().sum()
valores_nulos_por_columna

publisher       0
genres          0
app_name        0
title           0
url             0
release_date    0
tags            0
reviews_url     0
specs           0
price           0
early_access    0
id              0
developer       0
dtype: int64

**ELIMINO COLUMNAS QUE NO VAN A SER USADAS**

In [161]:
# elimino las columnas que no  necesito
df = df.drop(['publisher', 'app_name', 'url', 'tags', 'reviews_url', 'specs', 'early_access'], axis=1)

**ANALIZAMOS LOS DATOS DE LAS COLUMNAS**

 ---- *Columna GENRES*

In [162]:
# Vemos como esta compuesta la columna genres
df['genres'].value_counts

<bound method IndexOpsMixin.value_counts of 88310         [Action, Casual, Indie, Simulation, Strategy]
88311                  [Free to Play, Indie, RPG, Strategy]
88312     [Casual, Free to Play, Indie, Simulation, Sports]
88313                           [Action, Adventure, Casual]
88315                       [Action, Adventure, Simulation]
                                ...
120439                   [Action, Adventure, Casual, Indie]
120440                [Casual, Indie, Simulation, Strategy]
120441                            [Casual, Indie, Strategy]
120442                          [Indie, Racing, Simulation]
120443                                      [Casual, Indie]
Name: genres, Length: 22530, dtype: object>

In [163]:
# Desanidamos la lista dentro de la columna
df = df.explode('genres')

In [164]:
# Pasamos a variables dummies el contenido de genres
dummies_genres = pd.get_dummies(df['genres'], prefix='genres')

In [165]:
# Concatenar las variables dummies al DataFrame original y eliminar la columna original
df = pd.concat([df, dummies_genres], axis=1)
df.drop('genres', axis=1, inplace=True)

In [166]:
# Verificamos el cambio. 
df.head(3)

,title,release_date,price,id,developer,genres_Action,genres_Adventure,genres_Animation &amp; Modeling,genres_Audio Production,genres_Casual,...,genres_Photo Editing,genres_RPG,genres_Racing,genres_Simulation,genres_Software Training,genres_Sports,genres_Strategy,genres_Utilities,genres_Video Production,genres_Web Publishing
88310,Lost Summoner Kitty,2018-01-04,4.99,761140,Kotoshiro,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
88310,Lost Summoner Kitty,2018-01-04,4.99,761140,Kotoshiro,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
88310,Lost Summoner Kitty,2018-01-04,4.99,761140,Kotoshiro,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [167]:
# Tomamos a partir de la quinta columna y cambiamos los True o False a 1 y 0
df[df.columns[5:]] = df[df.columns[5:]].astype(int)

 ---- *Columna RELEASE_DATE*

In [168]:
# se extrae el año unicamente de la columna release date
df['release_date'] = df['release_date'].str.extract(r'(\d{4})')

In [169]:
df.head(2)

,title,release_date,price,id,developer,genres_Action,genres_Adventure,genres_Animation &amp; Modeling,genres_Audio Production,genres_Casual,...,genres_Photo Editing,genres_RPG,genres_Racing,genres_Simulation,genres_Software Training,genres_Sports,genres_Strategy,genres_Utilities,genres_Video Production,genres_Web Publishing
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

 ---- *Columna PRICE*

In [170]:
df['price'].unique()

array([4.99, 'Free To Play', 'Free to Play', 0.99, 3.99, 18.99, 29.99,
       10.99, 2.99, 1.59, 14.99, 1.99, 59.99, 9.99, 6.99, 7.99, 39.99,
       'Free', 19.99, 7.49, 8.99, 12.99, 5.99, 2.49, 15.99, 1.25, 24.99,
       17.99, 61.99, 3.49, 11.99, 13.99, 'Free Demo', 'Play for Free!',
       34.99, 1.49, 32.99, 99.99, 14.95, 69.99, 16.99, 79.99, 49.99,
       13.98, 149.99, 771.71, 'Install Now', 21.99, 89.99,
       'Play WARMACHINE: Tactics Demo', 0.98, 139.92, 4.29, 'Free Mod',
       54.99, 64.99, 74.99, 0.89, 0.5, 'Play Now', 299.99, 1.29, 119.99,
       44.99, 3.0, 15.0, 1.39, 'Free HITMAN™ Holiday Pack', 2.0, 4.0,
       1.95, 1.5, 6.66, 26.99, 399.99, 31.99, 20.0, 40.0, 5.0, 3.33,
       38.85, 71.7, 995.0, 5.49, 27.49, 3.39, 6.0, 19.95, 20.99, 499.99,
       27.99, 199.99, 4.68, 131.4, 44.98, 202.76, 2.3, 0.95, 36.99,
       172.24, 249.99, 2.97, 10.96, 2.66, 6.48, 10.0, 1.0, 11.15,
       'Play the Demo', 49.0, 199.0, 99.0, 87.94, 0.49, 9.98, 9.95, 12.89,
       6.49, 1.87, 41.99, 4.49, 289.99, 23.96, 5.65, 12.0, 129.99, 23.99,
       13.37, 189.96, 59.95, 160.91, 'Third-party'], dtype=object)

In [171]:
# paso todos los valores a string
df['price'] = df['price'].astype(str)

In [172]:
# Cambio todos los string que contienen Free por 0.00
condicion = df['price'].str.contains('Free')
df.loc[condicion, 'price']='0.00'

In [173]:
# Cambio todos los string que contienen Install por 0.00
condicion = df['price'].str.contains('Install')
df.loc[condicion, 'price']='0.00'

In [174]:
# Cambio todos los string que contienen party por 0.00
condicion = df['price'].str.contains('party')
df.loc[condicion, 'price']='0.00'

In [175]:
# Cambio todos los string que contienen Play por 0.00
condicion = df['price'].str.contains('Play')
df.loc[condicion, 'price']='0.00'

In [176]:
# paso todos los valores de string a float
df['price'] = df['price'].astype(float)

In [177]:
df.columns

Index(['title', 'release_date', 'price', 'id', 'developer', 'genres_Action',
       'genres_Adventure', 'genres_Animation &amp; Modeling',
       'genres_Audio Production', 'genres_Casual',
       'genres_Design &amp; Illustration', 'genres_Early Access',
       'genres_Education', 'genres_Free to Play', 'genres_Indie',
       'genres_Massively Multiplayer', 'genres_Photo Editing', 'genres_RPG',
       'genres_Racing', 'genres_Simulation', 'genres_Software Training',
       'genres_Sports', 'genres_Strategy', 'genres_Utilities',
       'genres_Video Production', 'genres_Web Publishing'],
      dtype='object')

In [178]:
df.head()

,title,release_date,price,id,developer,genres_Action,genres_Adventure,genres_Animation &amp; Modeling,genres_Audio Production,genres_Casual,...,genres_Photo Editing,genres_RPG,genres_Racing,genres_Simulation,genres_Software Training,genres_Sports,genres_Strategy,genres_Utilities,genres_Video Production,genres_Web Publishing
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
88310,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [179]:
# Reseteamos el indice
df = df.reset_index(drop=True)

In [180]:
# normalizamos el nombre de algunas columnas
df.rename(columns={'genres_Animation &amp; Modeling': 'genres_Animation and Modeling'}, inplace=True)
df.rename(columns={'genres_Design &amp; Illustration': 'genres_Design and Illustration'}, inplace=True)
df.rename(columns={'id': 'item_id'}, inplace=True)

In [181]:
df.head(1)

,title,release_date,price,item_id,developer,genres_Action,genres_Adventure,genres_Animation and Modeling,genres_Audio Production,genres_Casual,...,genres_Photo Editing,genres_RPG,genres_Racing,genres_Simulation,genres_Software Training,genres_Sports,genres_Strategy,genres_Utilities,genres_Video Production,genres_Web Publishing
0,Lost Summoner Kitty,2018,4.99,761140,Kotoshiro,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [182]:
#Hacemos una consulta de prueba para ver los que han generado contenido gratis
df.loc[df['genres_Free to Play'] == 1]

,title,release_date,price,item_id,developer,genres_Action,genres_Adventure,genres_Animation and Modeling,genres_Audio Production,genres_Casual,...,genres_Photo Editing,genres_RPG,genres_Racing,genres_Simulation,genres_Software Training,genres_Sports,genres_Strategy,genres_Utilities,genres_Video Production,genres_Web Publishing
5,Ironbound,2018,0.00,643980,Secret Level SRL,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Real Pool 3D - Poolians,2017,0.00,670290,Poolians.com,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,SNOW - All Access Pro Pass,2018,18.99,774277,Poppermost Productions,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,SNOW - All Access Legend Pass,2018,29.99,774278,Poppermost Productions,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,SNOW - Starter Pack,2018,14.99,774271,Poppermost Productions,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55361,SCP: Secret Laboratory,2017,0.00,700330,Hubert Moszka,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55380,Aurora Trail,2017,0.00,755150,Screenhit Studios,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55408,Six Days of Snow,2017,0.00,754810,ebi-hime,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55434,Bloodworks,2018,0.00,717990,Engin Mercan,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55561,忍者村大战2,2018,0.00,754350,杭州分浪网络科技有限公司,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [183]:
df.columns

Index(['title', 'release_date', 'price', 'item_id', 'developer',
       'genres_Action', 'genres_Adventure', 'genres_Animation and Modeling',
       'genres_Audio Production', 'genres_Casual',
       'genres_Design and Illustration', 'genres_Early Access',
       'genres_Education', 'genres_Free to Play', 'genres_Indie',
       'genres_Massively Multiplayer', 'genres_Photo Editing', 'genres_RPG',
       'genres_Racing', 'genres_Simulation', 'genres_Software Training',
       'genres_Sports', 'genres_Strategy', 'genres_Utilities',
       'genres_Video Production', 'genres_Web Publishing'],
      dtype='object')

In [184]:
df.to_csv('../CSV/output_steaam_games.csv', index=False)